# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f8694838de39ce4a85bb4352ad0a910c8fdaef72529716e8109a14ac8ba45bbea2b1f82f509cc0e084fa87f71d70586d9e7834c65b94141ccb7793a1b4ee462

test:
  secret_key_base: 9a84b3399b6ec1fbc15da6b56ecc6ae92b52678953e816d11fe8957c69f1cc0d27e1879341f6c3c37e38be5648409d7ab7f6a274a74079e4c3a1b18e3b831476

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
